/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestordecitas.pantallas;

import entidades.Cita;
import entidades.Especialidad;
import entidades.Medico;
import entidades.Paciente;
import gestordecitass.GestorDeCitas;
import javax.swing.JFrame;

/**
 *
 * @author PierooA.S
 */
public class JFrameCita extends javax.swing.JFrame {

    //El formulario padre 
    private JFrameGestorDeCitas padre;
    private Cita cita;
    private boolean estoyEditando = false;
    private Medico medicoSeleccionado;
    private Paciente pacienteSeleccionado;
    private Especialidad especialidadSeleccionada;
    /**
     * Creates new form JFramCitas
     */
    public JFrameCita(JFrameGestorDeCitas padre) {
        initComponents();
        this.padre=padre;
        
        cb_especialidad.removeAllItems();
        cb_especialidad.setEnabled(false);
        
        cb_hora.removeAllItems();
        for( String hora: GestorDeCitas.horasDisponibles){
            cb_hora.addItem(hora);
        }
        cb_fecha.removeAllItems();
        for( String fecha: GestorDeCitas.fechasDisponibles){
            cb_fecha.addItem(fecha);
        }
        
        
        
    }
    public JFrameCita(JFrameGestorDeCitas padre,Cita cita) {
        initComponents();
        this.padre=padre;
        this.cita=cita;
        this.estoyEditando=true;
        this.btn_bus_pac.setVisible(false);
        this.btn_bus_med.setVisible(false);
        this.btn_guardar.setVisible(false);
        lblTitulo.setText("Visualizar Cita");
        this.txt_med.setText(cita.getMedico().getDatosMostrar());
        this.txt_pac.setText(cita.getPaciente().getDatosMostrar());
        cb_especialidad.removeAllItems();
        cb_especialidad.addItem(cita.getEspecialidad().getNombre());
        
        cb_fecha.removeAllItems();
        cb_fecha.addItem(GestorDeCitas.fechasDisponibles.get(cita.getFecha()));
        
        cb_hora.removeAllItems();
        cb_hora.addItem(GestorDeCitas.horasDisponibles.get(cita.getHora()));
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_pac = new javax.swing.JTextField();
        txt_med = new javax.swing.JTextField();
        btn_bus_pac = new javax.swing.JButton();
        btn_bus_med = new javax.swing.JButton();
        cb_especialidad = new javax.swing.JComboBox<>();
        cb_fecha = new javax.swing.JComboBox<>();
        cb_hora = new javax.swing.JComboBox<>();
        btn_salir = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_bus_pac.setText("Buscar Paciente");
        btn_bus_pac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bus_pacActionPerformed(evt);
            }
        });

        btn_bus_med.setText("Buscar Medico");
        btn_bus_med.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bus_medActionPerformed(evt);
            }
        });

        cb_especialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_especialidad.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cb_especialidadPropertyChange(evt);
            }
        });

        cb_fecha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cb_hora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitulo.setText("Nueva Cita");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cb_especialidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_med, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                            .addComponent(txt_pac, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cb_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cb_hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_salir))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_guardar)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btn_bus_pac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_bus_med, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_pac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_bus_pac))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_med, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_bus_med))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_especialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_salir)
                    .addComponent(btn_guardar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // TODO add your handling code here:
        salir();
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_bus_medActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bus_medActionPerformed
        // TODO add your handling code here:
        
        JFrameMedicos pantallaMedicos=new JFrameMedicos(this);
        pantallaMedicos.setLocationRelativeTo(this);
        pantallaMedicos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_bus_medActionPerformed

    private void btn_bus_pacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bus_pacActionPerformed
        // TODO add your handling code here:
        JFramePacientes pantallaPacientes=new JFramePacientes(this);
        pantallaPacientes.setLocationRelativeTo(this);
        pantallaPacientes.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_bus_pacActionPerformed

    public void guardarCita(){
       
        if(medicoSeleccionado!=null &&pacienteSeleccionado!=null){
            int indiceSeleccionado=cb_especialidad.getSelectedIndex();
            especialidadSeleccionada = medicoSeleccionado.getEspecialidades().get(indiceSeleccionado);
        
            cita = new Cita(medicoSeleccionado,pacienteSeleccionado,especialidadSeleccionada);
            
            cita.setFecha(cb_fecha.getSelectedIndex());
            cita.setHora(cb_hora.getSelectedIndex());
            
            this.padre.agregarCita(cita);
            
        }
        
        
        
    }
    
    public void setPaciente(Paciente paciente){
        this.pacienteSeleccionado=paciente;
        txt_pac.setText(paciente.getDatosMostrar());
    }
    public void setMedico(Medico medico){
        this.medicoSeleccionado=medico;
        
        txt_med.setText(this.medicoSeleccionado.getDatosMostrar());
        cb_especialidad.removeAllItems();
        for(Especialidad espec : medico.getEspecialidades()){
            cb_especialidad.addItem(espec.getNombre());
        }
        cb_especialidad.setEnabled(true);
        
        
    }
    public void setEspecialidad(Especialidad especialidad ){
        this.especialidadSeleccionada=especialidad;
    }
    
    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        // TODO add your handling code here:
        guardarCita();
        salir();
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void cb_especialidadPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cb_especialidadPropertyChange
        // TODO add your handling code here:
        if(this.medicoSeleccionado!=null){
            Especialidad Espec =this.medicoSeleccionado.getEspecialidades().get(cb_especialidad.getSelectedIndex());
        setEspecialidad(Espec);
        }
        
    }//GEN-LAST:event_cb_especialidadPropertyChange

    /**
     * Debe abrir la ventana Paciente y 
     * permitirme escoger un paciente
     */
    private void buscarPaciente(){
        JFramePacientes paciente = new JFramePacientes(this);
        paciente.setLocationRelativeTo(null);
        paciente.setVisible(true);
    }
    
    private void salir(){
        //Muestra la ventana padre
        padre.setVisible(true);
        //Elmina esta ventana para no ocupar memoria
        this.dispose();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameCita(new JFrameGestorDeCitas()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bus_med;
    private javax.swing.JButton btn_bus_pac;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_salir;
    private javax.swing.JComboBox<String> cb_especialidad;
    private javax.swing.JComboBox<String> cb_fecha;
    private javax.swing.JComboBox<String> cb_hora;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txt_med;
    private javax.swing.JTextField txt_pac;
    // End of variables declaration//GEN-END:variables
}
